Ajustement d'affichage du menu de navigation mobile
openpcrs/pcrs.beta.gouv.fr pull request #132
Opened 2023-03-29 09:26 UTC by Maxine-Le-Pennec

Cette PR corrige différent problème d'affichage du menu de navigation en version mobile 

- Ajustement de l'index :  le menu de navigation en version mobile apparaissait sous le `header` au moment de l’affichage.
- Ajustement du padding manquant aux éléments de la liste.
- Correction de la disparition du menu mobile lors de l'agrandissement de la fenêtre (et au passage au mode desktop)

### **AVANT**
<img width="502" alt="Capture d’écran 2023-03-29 à 11 03 54" src="https://user-images.githubusercontent.com/66621960/228489713-9cc6dab0-6ffc-456d-8f28-716bd6eb815b.png">

https://user-images.githubusercontent.com/66621960/228489574-9f4fc20c-7f67-4867-99a3-96021d92cc18.mov

### **APRÈS**
<img width="502" alt="Capture d’écran 2023-03-29 à 11 03 39" src="https://user-images.githubusercontent.com/66621960/228489885-7ca4ddd4-6cdf-435d-aab6-726cc9952af9.png">

2023-03-29 10:24 UTC, GllmR requested changes
Il y a un souci avec la page du blog : 

![Capture d’écran 2023-03-29 à 12 21 54](https://user-images.githubusercontent.com/56537238/228504806-e3b13ce1-d322-4c61-8c48-39829ba28683.png)

Les tags et la pagination ont certainement un `z-index: 999` 🙂

2023-03-29 10:24 UTC, GllmR commented on components/header.js
> +        z-index: 999;
Même si je comprends, ça reste toujours une mauvaise pratique de faire ça.
C'est signe qu'on ne maitrise pas les différentes couches de l'interface.

2023-03-31 11:04 UTC, Maxine-Le-Pennec commented on components/header.js
> +        z-index: 999;
Même pas... Investigation en cours

2023-04-12 15:36 UTC, GllmR commented on lib/blog.js
> +const KEY = process.env.GHOST_KEY || 'ghost.pcrs.beta.gouv.fr'
?

Je ne crois pas que ça concerne cette PR 😅

2023-04-12 15:46 UTC, GllmR approved these changes

2023-04-12 16:08 UTC, merged