Refonte de l'ergonomie des formulaires
openpcrs/pcrs.beta.gouv.fr pull request #155
Opened 2023-04-12 12:57 UTC by Maxine-Le-Pennec

Cette PR améliore des soucis d'ergnomie présents sur les formulaires d'ajouts de livrables, d'acteurs, de périmètres et de subvention.

- Le bouton d'ajout d'un `acteur`, d'une `subvention`, d'un `périmètre` ou d'un `livrable` se trouve en dessus de la liste d'items.

- Le bouton d'ajout disparait lorsque le formulaire est ouvert afin d'alléger l'interface et ne pas gêner l'utilisateur.

- Le formulaire d'édition s'ouvre directement sous l'item concerné. 
- À l'édition/ajout, les "cartes d'information" sont grisées et la suppression/édition d'un item n'est pas possible tant que le formulaire ouvert n'est pas validé ou annulé.

Close  #166

### **Formulaire fermé**
<img width="1360" alt="Capture d’écran 2023-04-12 à 14 48 06" src="https://user-images.githubusercontent.com/66621960/231463492-3f474a84-b6a3-4376-a0a3-a5f9c19e377d.png">

------------------------------------------------

### **Formulaire ouvert**
![Capture d’écran 2023-04-20 à 16 10 30](https://user-images.githubusercontent.com/66621960/233393898-cbee735f-f049-4ba9-80cc-6a82173931cf.png)
![Capture d’écran 2023-04-20 à 16 10 13](https://user-images.githubusercontent.com/66621960/233393902-0df8231e-01a5-477c-9fd7-54aa14d19bd0.png)

2023-04-13 10:00 UTC, GllmR requested changes
Il y a un petit souci avec le séparateur : 
Il s'affiche en haut et uniquement lorsqu'un champ possède plusieurs entrées.

![ordre_formulaire](https://user-images.githubusercontent.com/56537238/231725192-a1d4f75a-e3ea-4748-811e-221e5447d439.gif)

2023-04-17 15:10 UTC, GllmR requested changes
Le bouton "Ajouter une étape" est resté en haut : 

![image](https://user-images.githubusercontent.com/56537238/232528746-be37127a-2cae-4ff9-99f0-bb111c4a1fdf.png)

2023-04-17 15:13 UTC, GllmR requested changes
Quand on édite un champ dans une liste, le formulaire s'ouvre en dessous de la liste.

On ne pourrait pas faire en sorte qu'il s'ouvre en dessous de l'objet édité ?

![image](https://user-images.githubusercontent.com/56537238/232530224-8ce19a19-baba-4b74-afb7-696b291444d9.png)

2023-04-18 07:20 UTC, Maxine-Le-Pennec commented
> Quand on édite un champ dans une liste, le formulaire s'ouvre en dessous de la liste.
> 
> On ne pourrait pas faire en sorte qu'il s'ouvre en dessous de l'objet édité ?
> 
> ![image](https://user-images.githubusercontent.com/56537238/232530224-8ce19a19-baba-4b74-afb7-696b291444d9.png)

Ceci fera partie d'une PR à part entière

2023-04-18 07:37 UTC, Maxine-Le-Pennec commented
> > > Quand on édite un champ dans une liste, le formulaire s'ouvre en dessous de la liste.
> > > On ne pourrait pas faire en sorte qu'il s'ouvre en dessous de l'objet édité ?
> 
> > Ceci fera partie d'une PR à part entière
> 
> Pourquoi ?
> 
> C'est un problème d'ergonomie, on est dans la réorganisation du composant, autant le faire dans cette PR.

On est dans le repositionnement des boutons d'ajout.
Changer le formulaire de place demande un peu de réorganisation de code pour que tout soit lisible et propre. Je préfère le faire dans une autre PR

2023-04-21 10:22 UTC, GllmR requested changes

2023-04-21 10:22 UTC, GllmR commented on components/suivi-form/perimetres/perimetre-form.js
> +const renderItem = (item, isHighlighted) => {
Il me semble que ce code se répète à différents endroits, est-ce qu'on pourrait en faire un composant ?

2023-04-21 10:22 UTC, GllmR commented on components/suivi-form/perimetres/perimetre-form.js
> +
Idem, voir pour fusionner ces parties

2023-04-21 10:22 UTC, GllmR commented on components/suivi-form/perimetres/perimetre-form.js
> +        handlePerimetres([...perimetres].map((perimetre, idx) => {
Idem `index` vs `find`

2023-04-21 10:22 UTC, GllmR commented on components/suivi-form/subventions/subvention-form.js
> +
Idem petites fautes, fusion, `find` vs `index`  😅

2023-04-21 10:22 UTC, GllmR commented on components/suivi-form/subventions/subvention-form.js
> +const NATURES = [
Est-ce qu'il ne serait pas intéressant d'avoir un gros objet dans un fichier externe avec toutes ces valeurs (NATURES, TYPES, etc) ?

Ce serait plus simple lorsqu'il faut modifier une valeur si le modèle change ou si la description d'un champ doit être modifiée.

2023-04-24 16:05 UTC, Maxine-Le-Pennec commented on components/suivi-form/acteurs/acteur-form.js
> +    if (name === 'siren' && !isSirenValid) {
Je n'ai pas compris ce que tu veux dire par là : `La vérification de siren et de phone devrait être dans le même ordre.`.
Cette vérification est faite pour chaque input qui appelle cette fonction. Le champ `siren` ignorera la vérification du numéro de téléphone car il n'est pas concerné et vice versa.

Je ne vérifie pas `input` pour `siren` sinon l'erreur s'affiche dès le premier caractère entré :)
![Capture d’écran 2023-04-24 à 18 05 01](https://user-images.githubusercontent.com/66621960/234053297-ffd690e7-0f75-4f9f-b49c-f319baffde65.png)

2023-04-24 16:09 UTC, GllmR commented on components/suivi-form/acteurs/acteur-form.js
> +    if (name === 'siren' && !isSirenValid) {
Dans le premier, tu fais `name === 'siren' && !isSirenValid` et dans le suivant `!isPhoneNumberValid && name === 'phone'` , c'est du chipotage, mais ça aide la lecture ;)

2023-04-26 08:37 UTC, GllmR approved these changes

2023-04-26 09:03 UTC, merged