Suivi-projet : Gestion des projets superposés
openpcrs/pcrs.beta.gouv.fr pull request #157
Opened 2023-04-12 14:43 UTC by GllmR

## Détails : 

Il peut arriver qu’un territoire soit couvert par plusieurs projets PCRS.
Actuellement, on ne peut afficher les détails que pour le projet le plus récent.

## Modifications : 

- Ajout d'un message dans la fenêtre contextuelle de la carte qui indique que le projet survolé possède plusieurs projets PCRS.
- Ajout d'un sélecteur dans l'en tête du panneau latéral permettant de sélectionner les projets.

## Captures : 

![Capture d’écran 2023-04-12 à 16 28 49](https://user-images.githubusercontent.com/56537238/231490804-1d4b6ef4-176b-4309-b1f6-261bd18c060a.png)

![Capture d’écran 2023-04-12 à 16 29 53](https://user-images.githubusercontent.com/56537238/231490887-f1f6dd16-ab8f-43c8-9d45-4511c66cdd67.png)

![Capture d’écran 2023-04-12 à 16 32 23](https://user-images.githubusercontent.com/56537238/231491025-17a95414-0365-4843-bb91-34e14743cdb4.png)

![Enregistrement de l’écran 2023-04-12 à 14 42 02](https://user-images.githubusercontent.com/56537238/231492839-0b8cee3f-8ac0-4988-b4a6-650f9524eb53.gif)

2023-04-14 08:35 UTC, Maxine-Le-Pennec requested changes
J'ajoute une petite proposition de design pour la popup !

<img width="678" alt="Capture d’écran 2023-04-14 à 10 13 55" src="https://user-images.githubusercontent.com/66621960/231990583-3f7a64b2-4baa-4266-a3fc-52b2bebc47ec.png">

2023-04-14 08:35 UTC, Maxine-Le-Pennec commented on pages/suivi-pcrs.js
> +
Tu penses que ça serait pertinent de set un message d'erreur si le `Promise.all` échoue ?

2023-04-14 08:35 UTC, Maxine-Le-Pennec commented on pages/suivi-pcrs.js
> +  const [projets, setProjets] = useState()
Est-ce que tu penses que c'est possible de se limiter à la state `projets` et de créer une constante `projet` qui correspond à `projets[0]` si `projets > 1` ?

2023-04-14 08:35 UTC, Maxine-Le-Pennec commented on components/map/popup.js
> +const Popup = ({projet, otherProjets}) => {
Le nom n'est pas très pertinent. On s'attend à une collection et il s'agit d'un nombre

2023-04-14 08:35 UTC, Maxine-Le-Pennec commented on components/map-sidebar/project-header.js
> +  onProjetChange: null
Alors ce n'est pas que là, mais je me demande si ce n'est pas mieux de mettre `fonctionToto() {}` au lieu de `null` lorsqu'une fonction n'est pas `required`. Je me le suis toujours un peu demandé...

2023-04-14 10:17 UTC, GllmR commented on components/map-sidebar/project-header.js
> +  onProjetChange: null
Ça va retourner `undefined`, je ne suis pas sûr que ça change grand-chose, je vais vérifier.

2023-04-17 15:15 UTC, Maxine-Le-Pennec commented on components/map-sidebar/index.js
> +        projets={projets}
Un petit espace moche mais c'est pas le drame

2023-04-17 15:15 UTC, Maxine-Le-Pennec commented on components/map-sidebar/project-header.js
> +  onProjetChange: null
Je viens de relire le code et je me demande à quel moment `onProjetChange` n'est pas obligatoirement utilisé. J'ai l'impression que c'est une fonction forcément exploitée

2023-04-17 15:21 UTC, GllmR commented on components/map-sidebar/index.js
> +        projets={projets}
J'ai pas compris ce que tu voulais dire

2023-04-17 15:23 UTC, GllmR commented on components/map-sidebar/project-header.js
> +  onProjetChange: null
S'il n'y a pas plusieurs projets sur le territoire en question, la fonction ne sera jamais utilisée

2023-04-17 15:35 UTC, Maxine-Le-Pennec approved these changes

2023-04-18 13:15 UTC, merged