Utilisation d'une seule page formulaire
openpcrs/pcrs.beta.gouv.fr pull request #162
Opened 2023-04-14 15:14 UTC by Maxine-Le-Pennec

- Afin de réduire la duplication de code et de mieux organiser le formulaire, l'utilisateur y accède maintenant via une seule page : `/formulaire-suivi`

- La page `[id].js` est supprimée au profit d'une vérification de la présence d'une query dans l'url au chargement de la page. Si un id est trouvé et valide, les valeurs par défaut du formulaire seront celles du projet récupéré via cet id, le passant ainsi en mode édition.

2023-04-14 21:32 UTC, tmerlier requested changes

2023-04-14 21:32 UTC, tmerlier commented on components/suivi-form/index.js
> +  const [subventions, setSubventions] = useState(initialProject?.subventions || [])
Donne une valeur par défaut à `initialProject` dans `SuiviForm.defaultProps`. Ça évitera les `||` qui alourdi la lecture du code.

2023-04-14 21:52 UTC, tmerlier requested changes

2023-04-14 21:52 UTC, tmerlier commented on components/suivi-form/index.js
>    const handleSubmit = async event => {
`useCallback` pour éviter des re-renders inutiles.

2023-04-14 21:52 UTC, tmerlier commented on components/suivi-form/index.js
> +      throw new Error(initialProject ? 'Une erreur a eu lieu lors de la modification du suivi' : 'Une erreur a eu lieu lors de la création du suivi')
Cette erreur n'est jamais récupérée.

2023-04-14 21:52 UTC, tmerlier commented on components/suivi-form/index.js
>    const handleSubmit = async event => {
Cette fonction mérite d'être découpée, elle est assez longue et complexe.

2023-04-17 16:06 UTC, GllmR commented
Lorsque je sélectionne un projet pour l'éditer, j'ai une erreur: 
```
Warning: Failed prop type: The prop `subventions` is marked as required in `Subventions`, but its value is `null`
```

2023-04-20 09:16 UTC, GllmR requested changes

2023-04-20 09:16 UTC, GllmR commented on components/suivi-form/index.js
> -     `}</style>
Il manque un espace

2023-04-21 10:39 UTC, GllmR approved these changes

2023-04-21 10:40 UTC, merged