Refonte de la gestion d'erreur du formulaire
openpcrs/pcrs.beta.gouv.fr pull request #179
Opened 2023-05-03 14:55 UTC by Maxine-Le-Pennec

Cette PR présente un nouveau système de gestion des inputs et de leurs erreurs. Le système actuel ne permet que très peu de souplesse dans la modification du code, qui est plus difficile à lire et interpréter.

1. Des messages d'erreurs cohérents à la validation de chaque formulaire de section, sous les champs (message ciblé) et au niveau du bouton de validation (message non ciblé et plus généraliste). 

- Les erreurs sont vérifiées et affichées, si présente, à la soumission du formulaire de section. 
- Si l'erreur dans un champ est corrigé, le message d'erreur inhérent à ce champ disparait.
- Si toutes les erreurs sont corrigées, même avant revalidation du formulaire, le message d'alerte général disparait.

2. La refonte permet de centraliser la gestion des champs via un hook `useInput` qui renvoie également l'erreur inhérente à chaque input.

### **Hook `useInput`** :

**Prend en arguments** : 
- `initialValue`=> valeur initiale de l'input (non-requis),  
- `checkValue` => function retournant le message d'erreur inhérent à chaque input (non requis), 
- `isRequired` => booléen indiquant si le champ est requis. 

**Retourne** : 
- `input` => valeur du champ,
- `setInput` => méthode de récupération de la valeur du champ (`e.target.value`),
- `error` => message d'erreur inhérent à au champ,
- `setIsValueValid` =>  méthode permettant de rendre valide/invalide un champ,
- `isValueValid` => booléen indiquant si l'input et valide ou non.

2023-05-15 14:18 UTC, GllmR requested changes

2023-05-15 14:18 UTC, GllmR commented on components/suivi-form/livrables/livrable-form.js
> +  const [dateLivraison, setDateLivraison, DateLivraisonError] = useInput({})
`dateLivraisonError`

2023-05-16 11:09 UTC, Maxine-Le-Pennec commented on components/suivi-form/acteurs/utils/error-handlers.js
> +}
C'est déjà le cas :) 
`emailChecker.test(mail) || !mail` vérifie si il y a un email ou si celui ci est valide. Si c'est le cas, il renvoie `true`

2023-05-17 13:07 UTC, GllmR commented on components/suivi-form/acteurs/utils/error-handlers.js
> +}
?

Non, s'il n'y a pas de mail, tu renvoies "true"

2023-05-19 08:53 UTC, GllmR approved these changes

2023-05-19 08:56 UTC, merged