Création d'une contexte d'authentification
openpcrs/pcrs.beta.gouv.fr pull request #185
Opened 2023-05-09 08:42 UTC by Maxine-Le-Pennec

Cette PR ajoute un contexte permettant de stocker et récupérer le token d'authentification. 

Le token renvoie : 
`isAdmin` : _<boolean>_ Désigne si l'utilisateur bénéficie ou non du statut d'administrateur.
`token` : _<string>_ Token d'authentification.
`storeToken` : _<func>_ Méthode de stockage du token dans le `localStorage`.
`setToken`: _<func>_ Méthode de récupération de la valeur de l'input recevant le token

2023-05-15 15:35 UTC, GllmR requested changes
Il serait peut-être intéressant d'attendre le prochain changement par rapport à la gestion des rôles (editeur / adminitrateur) qui devrait arriver bientôt.

2023-05-15 15:35 UTC, GllmR commented on components/suivi-form/index.js
> +
Je ne comprend pas ce que fait ce useEffect.

Il passe `isLoading` à `false` au chargement de la page, donc on ne devrait pas le voir ?

2023-05-16 13:11 UTC, Maxine-Le-Pennec commented on components/suivi-form/index.js
> +
J'avais une fraction de seconde où la modale apparaissait le temps que le contexte cherche le token mais j'ai du corriger ça sans m'en rendre compte par la suite :sweat_smile:

2023-05-17 14:13 UTC, GllmR approved these changes

2023-05-17 14:13 UTC, merged