Amélioration du responsive des cartes acteur et livrable
openpcrs/pcrs.beta.gouv.fr pull request #202
Opened 2023-05-29 15:00 UTC by Maxine-Le-Pennec

Un titre et/ou une adresse mail longue posait un problème de superposition et rendait les informations illisibles dans la carte `acteur`.
Le nouveau design d'affichage d'informations sur deux étages est aussi appliqué à la carte `livrable`.

**### AVANT**
<img width="1440" alt="Capture d’écran 2023-05-29 à 16 52 46" src="https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/9c1ec27e-2507-4eaa-ab30-92df26338e45">

### **APRÈS**
<img width="1440" alt="Capture d’écran 2023-05-29 à 16 51 23" src="https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/17e85723-9e35-4338-96ca-6eaf84236da0">
<img width="1439" alt="Capture d’écran 2023-05-29 à 16 51 00" src="https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/2c3a5026-73c3-4653-9317-32ca470d9a00">

2023-05-30 12:18 UTC, GllmR requested changes
On a perdu l'espace entre les différents "objets", je ne sais pas si une volonté, mais je trouve que c'est plus difficile à lire.

Avant :  

![image](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/56537238/86b336a3-dccb-4522-824c-439230629784)

Maintenant : 

![image](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/56537238/593ccc6b-af5a-47ea-b53e-474a86bc5d45)

2023-05-30 12:18 UTC, GllmR commented on components/suivi-form/acteurs/acteur-card.js
> +          {/* -------------------------------------- */}
?

2023-05-30 14:09 UTC, Maxine-Le-Pennec commented
> On a perdu l'espace entre les différents "objets", je ne sais pas si une volonté, mais je trouve que c'est plus difficile à lire.
> 
> Avant :
> 
> ![image](https://user-images.githubusercontent.com/56537238/241964022-86b336a3-dccb-4522-824c-439230629784.png)
> 
> Maintenant :
> 
> ![image](https://user-images.githubusercontent.com/56537238/241964248-593ccc6b-af5a-47ea-b53e-474a86bc5d45.png)

C'est un choix, je trouvais ça plus joli et plus clair de coller un peu plus le label et la valeur.
Tu penses que c'est préférable de retourner en arrière ?

2023-05-31 08:51 UTC, GllmR commented on components/suivi-form/acteurs/acteur-card.js
> +          {/* -------------------------------------- */}
Dans ce cas, tu peux mettre un commentaire  `top` et `bottom` , mais juste une ligne, c'est un peu bizarre oui :)

2023-05-31 10:04 UTC, GllmR approved these changes

2023-05-31 10:04 UTC, merged