Ajout de la déclaration d'accessibilité
openpcrs/pcrs.beta.gouv.fr pull request #23
Opened 2022-11-17 14:45 UTC by Maxine-Le-Pennec

Il est obligatoire d'ajouter une mention d'accessibilité du site dans le footer qu'il soit conforme au non.
Le rapport indique :

    L'état de conformité
    La réalisation ou non d'un audit
    Les points d'amélioration
    Information et contact
    Voie de recours
<img width="1440" alt="Capture d’écran 2022-11-17 à 15 27 16" src="https://user-images.githubusercontent.com/66621960/202476687-a3083a55-c1ba-491e-84d4-8034d3d8e52a.png">
<img width="1440" alt="Capture d’écran 2022-11-17 à 15 27 27" src="https://user-images.githubusercontent.com/66621960/202476711-64aa7770-5ae9-45ea-affb-fa1fe9b48463.png">

Close #2

2022-11-17 15:25 UTC, GllmR requested changes
Il y a également un problème avec la version mobile, il faut utiliser `fr-mx-md-*` pour gérer les appareils mobiles.

2022-11-17 15:25 UTC, GllmR commented on pages/declaration-accessibilite.js
> +      .fr-container {
Tu surcharges une classe existante, ce n'est pas nécessaire. Tu peux utiliser `fr-container--fluid` ainsi que `fr-grid-row fr-grid-row--center` et les ` fr-col` comme indiqué dans la [documentation](https://www.systeme-de-design.gouv.fr/elements-d-interface/fondamentaux-techniques/grille-et-points-de-rupture) du dsfr.

2022-11-17 15:25 UTC, GllmR commented on pages/declaration-accessibilite.js
> +      .illustration-wrapper {
Tu ajoutes des classes qui sont déjà intégrées dans le dsfr, cf mon autre commentaire.

2022-11-18 10:04 UTC, GllmR approved these changes

2022-11-18 10:04 UTC, merged

2022-11-18 10:04 UTC, flacombe commented
Je ne suis pas le plus pointu sur le sujet, toutefois ce qui est indiqué dans la capture d'écran au dessus et dans [declaration-accessibilite.js](https://github.com/openpcrs/pcrs.beta.gouv.fr/pull/23/files#diff-cf5dd9be5df145c98aa165ed131e744f73a26adbc978d1b7db3b3e6abb52c04d) me convient bien.