Recherche des acteurs sur la carte de suivi
openpcrs/pcrs.beta.gouv.fr pull request #243
Opened 2023-07-10 13:47 UTC by Maxine-Le-Pennec

Cette PR se concentre sur la mise en place d'un système de recherche d'un ou plusieurs projets en les filtrant par le nom d'un acteur. Il s'agit d'une évolution de la barre de recherche actuelle, qui se limitait à une recherche par APLC.

<img width="1438" alt="Capture d’écran 2023-07-10 à 15 47 08" src="https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/cbf05898-53de-4027-959b-588f946f3a50">

2023-07-11 16:10 UTC, GllmR requested changes
- Lorsqu'on tape une lettre dans la recherche, l'autocomplete affiche "aucun résultat" : Il faudrait ouvrir le panneau à partir de la deuxième lettre, ça ferait plus propre.
- Lorsqu'on efface la recherche, sans utiliser le bouton dédié, la carte n'affiche plus rien, ça ne devrait pas être le cas. Le filtre n'agit pas lorsqu'on lui envoie une chaine de caractères vide.
- Je trouve dommage d'enlever le filtre. On ne peut plus voir par exemple tous les "SDE", il faudra voir avec François si c'est un problème ou pas.

2023-07-12 13:52 UTC, Maxine-Le-Pennec commented on server/projets.js
> +        acteurs: projet.acteurs.map(acteur => acteur.nom?.toLowerCase() || ''),
Si passé à `null `au lieu de `"`
<img width="990" alt="Capture d’écran 2023-07-12 à 15 52 21" src="https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/802cfb89-87cd-463e-90b5-c728db6e9ead">

2023-07-13 07:58 UTC, GllmR commented on server/projets.js
> +        acteurs: projet.acteurs.map(acteur => acteur.nom?.toLowerCase() || ''),
C'est ton filtre qui est mal fait. Je ne pense pas qu'il soit utile de passer `''` en `lowerCase` 😁

2023-07-20 12:43 UTC, GllmR approved these changes

2023-07-20 12:45 UTC, merged