Ajout d’une API pour la gestion des administrateurs
openpcrs/pcrs.beta.gouv.fr pull request #253
Opened 2023-07-20 08:25 UTC by GllmR

>_Cette PR ajoute des fonctions CRUD pour la gestion des administrateurs du site PCRS._

Actuellement, les administrateurs du site utilisent le même jeton d’administration qui est dans le fichier `.env` .

Cette PR ajoute des routes permettant l’ajout / l’édition / la modification et la visualisation des administrateurs, afin de pouvoir facilement gérer les administrateurs du site sans avoir recours à un développeur.

## Parcours utilisateur : 

- Un administrateur ajoute l’adresse courriel d’un nouvel administrateur
- Le nouvel administrateur reçoit alors son jeton sur son adresse courriel
- Il est invité à se connecter sur la partie `/gestion-suivi` du site

## Modifications : 

- Ajout des fonctions CRUD 
- Ajout d’une fonction pour récupérer un administrateur par son token
- Mise à jour des index MongoDB
- Ajout d’un modèle de courriel pour les administrateurs
- Mise à jour du middleware permettant l’authentification sur le site
- Mise à jour des routes
- Ajouts de tests

2023-08-07 08:53 UTC, jdesboeufs requested changes

2023-08-07 08:53 UTC, jdesboeufs commented on server/index.js
> +import {addAdministrator, getAdministrators, updateAdministrator, deleteAdministrator, getAdministratorById, isDeletingHimself} from './admin/administrators.js'
En anglais le masculin ne l'emporte pas sur le féminin. C'est `isSelfDeleting` :)

2023-08-07 08:53 UTC, jdesboeufs commented on server/index.js
> +  .get(w(ensureAdmin), w(async (req, res) => {
Tu peux utiliser cette syntaxe plutôt qu'utiliser le même middleware partout :
 
```js
server.route(...)
  .all(w(ensureAdmin))
  .get(...)
  .delete(...)
```

2023-08-07 08:53 UTC, jdesboeufs commented on server/index.js
> +      throw createError(404, 'Jeton inconnu')
Administrateur inconnu plutôt ?

2023-08-07 08:53 UTC, jdesboeufs commented on server/index.js
> +    const administrator = await getAdministratorById(req.params.adminId)
Dans le cas présent on préfère en général utiliser un gestionnaire de paramètre :
```
server.param('adminId', ...)
```
Ça permet d'injecter directement `req.administrator`. Mais ça n'a rien d'obligatoire.

2023-08-07 08:53 UTC, jdesboeufs commented on server/admin/administrators.js
> +  return mongo.db.collection('administrators').find().toArray()
Je sais pas si c'est une bonne chose de retourner les tokens si tu n'en as pas besoin. Tu peux les enlever dans le `find({}, {projection: {token: 0}})` (syntaxe à vérifier).

2023-08-07 08:53 UTC, jdesboeufs commented on server/admin/administrators.js
> +    throw createError(404, 'Cet identifiant est introuvable')
C'est pas redondant avec l'erreur qui te as dans le contrôleur du coup ?

2023-08-07 15:59 UTC, GllmR commented on server/admin/administrators.js
> +  const deleted = await mongo.db.collection('administrators').deleteOne({_id: adminId})
Les projets ne sont pas rattachés à un éditeur précis, donc la suppression d'un administrateur n'empêchera pas la suppression ou l'édition d'un projet.

Les administrateurs ont la possibilité de supprimer n'importe quel projet existant.

2023-08-08 13:19 UTC, jdesboeufs approved these changes

2023-08-08 13:21 UTC, GllmR commented on README.md
> +>__Il est préférable de ne plus l’utiliser par la suite et de préférer les accès personnalisés.__
Hum, oui, je voulais plutôt dire "ne plus utiliser l'accès avec le jeton".
Je vais essayer de trouver une tournure plus précise.

2023-08-08 14:02 UTC, merged