Ajout de la gestion des administrateurs
openpcrs/pcrs.beta.gouv.fr pull request #264
Opened 2023-07-25 15:15 UTC by Maxine-Le-Pennec

**⚠️ Ne pas merger avant la PR Ajout d’une API pour la gestion des administrateurs [#253 ](https://github.com/openpcrs/pcrs.beta.gouv.fr/pull/253)**

La page `/gestion-suivi` permet à présent d'afficher la liste des administrateurs et de les gérer.
Au même titre que pour les porteurs, il est possible : 

- De rajouter un administrateur
- De supprimer un administrateur (autre que soit-même)
- De consulter les administrateurs actifs, les rechercher via une barre de recherche et trier leur ordre d'apparition.

L'utilisateur identifié se verra apparaitre dans la liste avec une icône différente.

### **Blocage de l'auto-suppression**
<img width="1273" alt="Capture d’écran 2023-07-25 à 17 01 17" src="https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/efe38f9b-faeb-4f20-b9d4-63e6c4fc3af2">

------------------------
### **Ajout d'un administrateur**
<img width="1418" alt="Capture d’écran 2023-07-25 à 17 01 05" src="https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/1fc3bc7a-5149-4d33-8eb4-01cd1c5a87ea">

------------------------
### **Liste des administrateurs**
<img width="1440" alt="Capture d’écran 2023-07-25 à 17 00 29" src="https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/eb48c499-95d5-4da6-bf08-7b28b19729b4">

2023-07-25 15:56 UTC, tmerlier requested changes

2023-07-25 15:56 UTC, tmerlier commented on components/gestion-admin/administrateur-list.js
> +        setErrorMessage('Il est impossible de révoquer ses propres droits administrateurs')
Si tu peux le détecter alors inutile de faire l'appel.

2023-07-25 15:56 UTC, tmerlier commented on components/gestion-admin/administrateur-list.js
> +        setErrorMessage(`Les droits administrateurs de ${nom} n’ont pas pu être révoqués`)
Il faudrait avoir la raison de l’échec.

2023-07-25 15:56 UTC, tmerlier commented on components/gestion-admin/administrateurs.js
> +      setAdmins(orderBy(administrators, [item => item.nom ? item.nom.toLowerCase() : 'N/A'.toLowerCase()], ['asc']))
On perd en lisibilité, je te propose de modifier un peu.

```suggestion
      const orderedAdministrators = orderBy(administrators, [item => item.nom ? item.nom.toLowerCase() : 'N/A'.toLowerCase()], ['asc']) // Order by name
      setAdmins(orderedAdministrators)
```

2023-07-25 15:56 UTC, tmerlier commented on components/gestion-admin/administrateurs.js
> +      setErrorMessages(errorMessages => ({...errorMessages, headerError: 'Le nouvel administrateur n’a pas pu être ajouté'}))
Pour éviter cette syntaxe un peu lourde, tu pourrais faire un custom hook `useErrors`.

2023-07-25 15:56 UTC, tmerlier commented on components/gestion-admin/administrateurs.js
> +  const [admins, setAdmins] = useState([])
Si j'ai bien compris, ce composant va récupérer les admins dès que possible. Dans ce cas, il est préférable de ne pas initialiser la valeur de state.

Ça permettra de différencier le premier rendu où les admins n'ont pas encore étaient récupérés et un rendu où aucun admin n'est trouvé.

2023-07-26 08:03 UTC, Maxine-Le-Pennec commented on components/gestion-admin/administrateurs.js
> +      setAdmins(orderBy(administrators, [item => item.nom ? item.nom.toLowerCase() : 'N/A'.toLowerCase()], ['asc']))
J'ai une fonction permettant de gérer ce cas que je n'avais pas intégré à cet endroit. L'outil `normalizeSort()` permettant de traiter les chaînes de caractères dans une fonction `orderBy` sera utilisée ici

2023-08-10 08:24 UTC, tmerlier requested changes

2023-08-10 08:24 UTC, tmerlier commented on components/gestion-admin/add-form.js
> +const AddForm = ({onClose, errorMessage, validationMessage, isAdmin, onSubmit}) => {
Le code est dupliqué mille fois…

```
const userTypeStr = isAdmin ? 'de l’administrateur' : 'du porteur'
...
label={`Nom ${userTypeStr}`}
````

NB: Attention à bien utilisais l’apostrophe `’` et pas la simple guillement `'` ;)

2023-08-10 08:24 UTC, tmerlier commented on components/gestion-admin/administrateurs.js
> +    setIsLoading(true)
```suggestion
    setIsLoading(true)
    clearError('fetchError')
```

2023-08-10 08:24 UTC, tmerlier commented on components/gestion-admin/administrateurs.js
> +      }, 1000)
Ce `setTimeout` n'est pas nécessaire.

2023-08-10 08:24 UTC, tmerlier commented on components/gestion-admin/header.js
> +      const filteredResults = items.filter(item => normalizeSort(item.email).includes(normalizeSort(searchValue)) || normalizeSort(item.nom || '').includes(normalizeSort(searchValue)))
Il faut au moins indenter et commenter, c'est assez illisible là.

2023-08-10 15:03 UTC, tmerlier approved these changes

2023-08-10 15:04 UTC, merged