Création d'un composant de notification toast
openpcrs/pcrs.beta.gouv.fr pull request #267
Opened 2023-07-28 08:21 UTC by Maxine-Le-Pennec

Un composant de notification de type `<Toast />` est mis en place afin de rendre plus visible les messages destinés à l'utilisateur et facilité la gestion des notifications.

Le design provient du composant [Alerte](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/alerte) du [DSFR](https://www.systeme-de-design.gouv.fr/).

Les props du composant sont les suivantes : 
`type` : _<string>_ => indique le type de notification à afficher et influera sur la couleur et l'icône. Ses valeurs peuvent être : `info` (default), `succes`, `warning`, `error`.
`title` : _<string>_ => Titre de la notification à afficher à l'utilisateur.
`isTriggered` : _<boolean>_ => Déclenche la notification.
`children` : _<node>_ => contenu de la notification.
`onClear` : _<function>_ => fonction de fermeture/disparition de la notification indépendamment du timer.

-------------------------
### **INFO**
<img width="1124" alt="Capture d’écran 2023-07-28 à 10 01 48" src="https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/c45d463d-191d-4e66-aec5-b0441ca83c9c">

-------------------------

### **SUCCESS**
<img width="1116" alt="Capture d’écran 2023-07-28 à 10 02 21" src="https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/cf85fc3c-18e7-42de-bb2e-7442f727b942">

-------------------------

### **WARNING**
<img width="1106" alt="Capture d’écran 2023-07-28 à 10 02 48" src="https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/c6273207-fec4-4891-96be-cfed69e8e3a4">

-------------------------

### **ERROR**
<img width="1098" alt="Capture d’écran 2023-07-28 à 10 03 04" src="https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/49675001-0251-49eb-bda0-3672ea6ff231">

 -------------------------

### **Animaton et positionnement** 
https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/85e48a95-09b4-4e7e-a8d0-381fd4eaa04f

2023-08-01 08:42 UTC, GllmR approved these changes

2023-08-01 08:46 UTC, tmerlier requested changes
Je ne comprends pas vraiment l'utilité d'un contexte ici.
Un contexte sert principalement à partager des informations à un ensemble de composant et faciliter l’accessibilité de ces informations profondément dans l’arborescence.

Ici, il serait plus approprié d'utiliser un custom hook, uniformiser la création et le déclenchement des toasts.

2023-08-01 08:46 UTC, tmerlier commented on contexts/toaster.js
> +  const [toastType, setToastType] = useState('info')
Pourquoi gérer deux states ?

2023-08-04 07:50 UTC, tmerlier requested changes
Tu as prévu un délai de 3000ms pour les toasts, il serait mieux de pouvoir contrôler cette variable pour adapter le temps d'affichage au message.

2023-08-04 07:50 UTC, tmerlier commented on hooks/toaster.js
> +      id: Date.now(),
On n'assure pas un identifiant unique ici. Même si le cas est rare, il reste possible de créer plusieurs toasts à la même milliseconde.

Un simple compteur incrémenté dédié à ce hook devrait suffire.

2023-08-04 07:50 UTC, tmerlier commented on hooks/toaster.js
> +    }, 3000)
Attention a bien nettoyer l'effet de bord.

```suggestion
    const timer = setTimeout(() => {
      removeToast(toast.id)
    }, 3000)
    
    return () => clearTimeout(timer)
```

2023-08-04 11:28 UTC, tmerlier approved these changes

2023-08-04 13:36 UTC, merged