Modification du visuel de la carte de suivi
openpcrs/pcrs.beta.gouv.fr pull request #297
Opened 2023-09-27 12:26 UTC by GllmR

Cette PR modifie quelques éléments visuels de la carte de suivi des projets PCRS : 

- On affiche désormais les contours de département (Fix #292)
- Léger élargissement des contours des projets
- Les voies navigables (Ferry) sont masquées

### Captures : 
#### Avant : 

![image](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/56537238/47433352-65b2-460f-afdb-f5de7628dccd)

![image](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/56537238/c4f4f8ef-82b8-4ac4-a688-d05b3269d4a5)

#### Après : 

![image](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/56537238/a2b46d5b-079b-4893-8eb1-c78b2288b00d)

![image](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/56537238/972a8fba-a45f-4035-a646-3f14f5fb9e13)

2023-09-27 13:05 UTC, Maxine-Le-Pennec approved these changes

2023-09-27 13:07 UTC, tmerlier requested changes

2023-09-27 13:07 UTC, tmerlier commented on components/map/styles/vector.json
> +        "visibility": "none"
Je ne pense pas que ce layer soit utile dans tous les cas. À la place de passer `visibility: "none"`, il serait préférable de le supprimer tout simplement. 

Sauf si ce style est utilisé pour autre chose que la carte des de suivi, alors il pourrait être bien allégé en supprimant tous les autres layers inutile.

2023-09-27 13:07 UTC, tmerlier commented on components/map/map.js
> +      maplibreMap.addLayer(departementsContours)
Y a-t-il un intérêt à charger indépendamment chaque layer ? Le style `vector` étant le seul disponible, il serait certainement plus simple d'y définir directement tous les layers. 

En plus d'alléger un peu le code, on évite également de tenter de manipuler des layers qui ne sont pas encore chargés par exemple.

2023-09-29 08:32 UTC, Maxine-Le-Pennec approved these changes

2023-09-29 09:29 UTC, tmerlier requested changes

2023-09-29 09:29 UTC, tmerlier commented on components/map/map.js
> +    popupRoot.render(<Loader size='small' />)
À quoi sert ce chargement ? Je n'ai pas l'impression qu'il soit utilisait.

2023-09-29 09:29 UTC, tmerlier commented on components/map/map.js
> +      if (selectedId?.current && selectedId?.current !== projetId) {
```suggestion
      if (selectedId.current && selectedId.current !== projetId) {
```

2023-09-29 09:45 UTC, tmerlier approved these changes

2023-09-29 09:48 UTC, merged