[formulaire] Nettoyage du code de la section Acteurs
openpcrs/pcrs.beta.gouv.fr pull request #307
Opened 2023-09-29 16:08 UTC by Maxine-Le-Pennec

Le code présentait des soucis de lourdeur et de compréhension. 
Un nettoyage a été effectué afin de faciliter la lecture du code et supprimer les lignes superflues 

- Lors d'une erreur au submit concernant la présence d'un acteur porteur de projet, le message d'erreur s'affiche directement sous le bouton de validation du formulaire.
- Les fonctions permettant l'affichage des messages d'erreurs des inputs est déplacée dans le fichier` /suivi-form/acteurs/utils/error-handlers` et sont à présent réutilisables.
- Des doubles vérifications inutiles ont été supprimées
- Des states et props inutiles ont été supprimées 
- La méthode d'ajout/update d'un acteur est déclarée dans le parent du mini-formulaire Acteur

2023-10-02 08:32 UTC, GllmR commented on components/suivi-form/acteurs/acteur-form.js
> +  const [siren, setSiren, sirenError] = useInput({checkValue: !isFormValid && handleSirenError, isRequired: !isFormValid})
Je trouve que la variable `isFormValid` devrait s’appeler `hasError` et être `false` par défaut. Il me semble même qu’elle pourrait être supprimée, puisque si `errorMessage` n’est pas `null`, le formulaire n’est plus valide. Ça permettrait d’éviter la négation (`!isFormValid`).

Je ne comprends pas pourquoi le champ est requis en fonction de la validité du formulaire. Si le formulaire est valide, le champ n’est plus obligatoire ?

2023-10-02 12:31 UTC, tmerlier requested changes
Beaucoup trop de chose ne vont pas avec le composant `<ActeurForm/>`. Une grande partie de la logique devrait se trouver dans le parent.

De manière générale, un composant de type formulaire devrait attendre les mêmes choses : 
- `initialeValues` : Les valeurs d'initialisation de tous les champs. Cela permet d'ouvrir un formulaire pré-rempli ou vide.
- `onSubmit` : Pour soumettre le formulaire
- `onCancel` : Pour annuler une création ou une édition
- `isLoading` (optionnel) : Dans le cas où la soumission est asynchrone

Pour ce qui est de la gestion des erreurs, il y a deux approches possibles. 
Soit, elle est effectuée par le parent au moment de la soumission de formulaire. Auquel cas, le composant formulaire a besoin de recevoir les erreurs détectées pendant la soumission. 
Soit le composant parent fourni une structure de validation au formulaire. Celle-ci peut par exemple contenir des méthodes de validation par champ. Son avantage sera de pouvoir valider les champs à chaud avant même de soumettre le formulaire.

La première méthode reste la plus simple et pourra toujours être mise en place.

2023-10-02 12:31 UTC, tmerlier commented on components/suivi-form/acteurs/index.js
> +  const handleActor = actor => {
Il serait préférable d'utiliser une `useCallback` car cette méthode est utilisée par une liste de composants enfants `<ActeurForm />`. Cela permettrait d'optimiser en limitant le nombre de rendus.

2023-10-02 12:31 UTC, tmerlier commented on components/suivi-form/acteurs/index.js
> +      {!isAdding && !updatingActorIndex && (
Pour une meilleure UX, le bouton devrait toujours être présent. C'est son attribut `disable` qui devrait être modifié afin d'être utilisable ou non.

2023-10-06 11:20 UTC, Maxine-Le-Pennec commented
### **Problèmes :** 

* Si un acteur APLC ou Porteur a déjà été ajouté, il est toujours possible de choisir ces rôles lors d'un ajout d'un acteur dans le cas où on laisse tous les champs vides au moment du choix du rôle. Si on remplit au moins un champ texte ou qu'on ferme et ré-ouvre le formulaire, les deux rôles sont bien disabled comme attendus. Il faudra alors rafraichir la page pour reproduire le comportement.

https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/209100a7-9aa7-4afb-a92d-c3ffa93dddd2

-------------------------------

* Si l'on souhaite éditer le rôle d'un acteur aplc ou porteur, il est impossible de lui redonner un de ces deux rôles si un autre type de rôle a été sélectionné. Il faudra créer un nouvel acteur pour voir ces options de nouveau sélectionnables. 
D'autres effets de bords ont lieu sur la sélection des rôles, comme le montre la vidéo
https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/cab6659d-c214-43a7-bc25-4077753af71e

-------------------------------

* Je trouve l'affichage d'une erreur via le debounce gênante. Je me sens un peu "agressée".

https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/36e20b5c-dab2-42b4-8e71-f4a3b40afe2e

-------------------------------

* Lorsqu'on édite un acteur existant, les champs `Part de financement`, `Montant du financement` et `Téléphone `sont vides même s'ils ont été initialement remplis.

![Capture d’écran 2023-10-06 à 12 38 08](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/f14b4422-5e09-456c-8001-90dd01879fd3)

-------------------------------

* Si l'on supprime le seul acteur entré, l'erreur `editedActor is null` se déclenche

![Capture d’écran 2023-10-06 à 13 07 59](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/53405a0b-1e29-4fbd-a9b3-7d151cef6d43)

2023-10-06 15:07 UTC, GllmR reviewed
En mode édition d'un projet : 
(un seul acteur présent dans la liste)
- Supprimer un acteur
- Remplir le formulaire pour ajouter un acteur

![image](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/56537238/5481fb5c-8bbc-4c85-ad19-9c7d3c945b27)

--- 

Dans l'input du numéro de téléphone, on ne peut pas entrer un numéro international puisqu'on ne peut pas entrer `+` . Ce qui fait qu'on peut valider un numéro `33600000000`, mais l’application va crasher au submit du formulaire car l’API ne valide pas ce numéro. (Le message d’erreur n‘est pas catché)

2023-10-09 08:47 UTC, GllmR approved these changes

2023-10-09 11:39 UTC, tmerlier approved these changes

2023-10-09 11:44 UTC, merged