[FIX] "section_activite_principale" peut être nul
openpcrs/pcrs.beta.gouv.fr pull request #308
Opened 2023-09-29 16:16 UTC by Maxine-Le-Pennec

Le composant `ActorsAutocompleteInput` permet d'afficher les acteurs ainsi que leur secteur d'activité principale (`section_activite_principale`). Or cette activité peut être non définie et affiche donc `undefined`

### **Solution :** 
Afficher la valeur "N/A" en cas de valeur nulle afin d'avertir l'utilisateur que cette information n'a pas été renseignée

<img width="463" alt="Capture d’écran 2023-09-29 à 18 12 04" src="https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/1a7d7689-a9de-4ab1-bb38-39663c79d42c">

Close  #306

2023-09-29 16:26 UTC, tmerlier requested changes

2023-09-29 16:26 UTC, tmerlier commented on components/suivi-form/acteurs/actors-autocomplete-input.js
> +      renderItem={item => `${item.nom_complet} - ${secteursActivites[item.section_activite_principale] || 'N/A'}`}
`N/A` est une abréviation pour dire "Not Applicable" ou "Not Available". Gardons "non renseignée" ou même rien du tout puisque visiblement ce champ peut ne pas être renseigné et donc ça n’a pas trop de sens.

2023-10-02 08:57 UTC, tmerlier approved these changes

2023-10-03 13:22 UTC, GllmR approved these changes

2023-10-03 13:22 UTC, merged