Réorganisation des dossier `/lib` et `/server`
openpcrs/pcrs.beta.gouv.fr pull request #312
Opened 2023-10-03 08:28 UTC by GllmR

Le dossier `/lib` contenait du code pour la partie client et la partie serveur du site.

Cette PR réorganise les fichiers de ce dossier afin de séparer le code client du code serveur.

- Création d’un dossier `/shared` contenant une fonction partagée
- Déplacement des fichiers relatifs au serveur vers le dossier `/server`
- Correction des chemins
- Renommage du dossier `/server` en `/backend`

2023-10-03 14:25 UTC, Maxine-Le-Pennec requested changes

2023-10-03 14:25 UTC, Maxine-Le-Pennec commented on backend/projets.js
> +import {findClosestEtape} from '../shared/find-closest-etape.js'
Est-ce qu'on pourrait utiliser le chemin déterminé dans `jsconfig.json` en faisant
`import {findClosestEtape} from '@/shared/find-closest-etape.js'` ?

2023-10-03 14:48 UTC, GllmR commented on backend/projets.js
> +import {findClosestEtape} from '../shared/find-closest-etape.js'
Il faudra le modifier puisque les liens contiendront le dossier `/backend` qui sera plus présent si on sépare les parties client / serveur.

2023-10-03 15:49 UTC, GllmR commented on backend/projets.js
> +import {findClosestEtape} from '../shared/find-closest-etape.js'
Il semble donc que ce ne soit pas indiqué dans notre cas (future séparation client / serveur)

2023-10-04 08:43 UTC, Maxine-Le-Pennec approved these changes

2023-10-04 09:04 UTC, tmerlier commented on backend/index.js
> +import {getProjetsGeojson} from './lib/projets.js'
Il me semble que l'on utilisait un dossier `models` dans ce genre de cas. Ça donnerait donc `/lib/models/projects.js`.

2023-10-04 11:34 UTC, tmerlier approved these changes

2023-10-04 12:55 UTC, merged