Ajout d'un composant Tab
openpcrs/pcrs.beta.gouv.fr pull request #325
Opened 2023-10-09 13:53 UTC by Maxine-Le-Pennec

Le composant `<Tab />` s'appuie sur le composant `Onglet - Tab` du DSFR.
Le chargement du fichier contenant les scripts du DSFR n'étant pour le moment pas possible sur un projet Nextjs, le comportement est reproduit et adapté dans le composant `<Tab />`.  
Ce nouveau composant est utilisé afin d'éviter les répétitions de code dans la page `/calculatrice` et `/gestion-suivi`. Il sera également exploité dans la future PR sur l'ajout du formulaire d'ajout de source.

Props reçues : 
`activeTab` : <_string_> => Onglet sélectionné. Permet de désigner l'onglet actif.
`tabs`  : <_collection_> => Liste d'onglets. L'objet se présente comme suit : `{label: 'Foo', isDisabled: true}` (`isDisabled` est non-requis)
`icon` : <_string_> => Désigne l'icône pouvant être affiché dans l'onglet (non-requis)
`children` : <_node_> => Contenu affiché lors de la sélection de l'onglet
`handleActiveTab` : <_function_> => Gère la sélection des onglets

2023-10-10 08:14 UTC, GllmR requested changes

2023-10-10 08:14 UTC, GllmR commented on components/ui/tab.js
> +        border: 1px solid #dddddd;
Je ne pense pas que ce soit nécessaire, ça crée une double ligne :

Avant : 

![image](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/56537238/a84e4d4a-bbc3-45a2-9840-a11f104a73ac)



Après : 

![image](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/56537238/a8b4a587-1603-4660-8a5a-e485e3ec6c82)

2023-10-10 08:14 UTC, GllmR commented on pages/calculatrice.js
> +          }
```
tabs={[
    {value: 'territoire', label: 'Estimation à partir d’un territoire'},
    {value: 'fichier', label: 'Estimation à partir de la taille d’un fichier'}
  ]}
```

2023-10-10 08:14 UTC, GllmR commented on pages/gestion-suivi.js
> +          tabs={[{value: 'porteurs', label: 'Porteur de projets'}, {value: 'admin', label: 'Administrateurs'}, {value: 'changes', label: 'Projets édités récemment'}]}
```
tabs={[
    {value: 'porteurs', label: 'Porteur de projets'},
    {value: 'admin', label: 'Administrateurs'},
    {value: 'changes', label: 'Projets édités récemment'}
]}
```

2023-10-12 12:01 UTC, tmerlier requested changes

2023-10-12 12:06 UTC, tmerlier approved these changes

2023-10-12 12:07 UTC, GllmR approved these changes

2023-10-12 12:09 UTC, merged