Modification du modèle de données et connexion au scanner
openpcrs/pcrs.beta.gouv.fr pull request #330
Opened 2023-10-11 07:58 UTC by GllmR

Cette PR modifie le modèle de données et ajoute la connexion au scanner afin de récupérer l'id du stockage lié à un livrable.

## Modifications du modèle : 

Statuts des projets : 
Ajouts : 
- `convention_signee` 
- `marche_public_en_cours`

Modifications : 
- `production` -> `prod_en_cours`
- `produit` -> `controle_en_cours`
- `livre` -> `disponible`

Nouveaux champs dans `livrables` : 
- `stockage_public`
- `stockage`
- `stockageParams`
- `stockageId`

Ajout d'une fonction qui récupère un id de stockage pour le lier à son livrable.

> _Cette PR a besoin que la partie client soit mise à jour avec les nouveaux champs_

2023-10-11 11:51 UTC, tmerlier requested changes

2023-10-11 11:51 UTC, tmerlier commented on backend/lib/models/projets.js
> +  if (SCANNER_URL) {
Dans le cas contraire, il faudrait au moins un `console.error` pour qu'on puisse s'en rendre compte.

2023-10-11 11:51 UTC, tmerlier commented on backend/lib/models/projets.js
> +    const updatedLivrables = await Promise.all(livrables.map(async livrable => {
J'ajouterai un try/catch par sécurité. Si on catch alors on fait un `console.error` pour remonter le problème en cas d'échec et on renvoi `livrables`.

2023-10-11 11:51 UTC, tmerlier commented on backend/lib/projets-validator.js
> +      'object.unknown': 'Un clé est invalide en mode http'
```suggestion
      'object.unknown': 'Une clé est invalide en mode http'
```

2023-10-11 11:51 UTC, tmerlier commented on backend/lib/projets-validator.js
> +  stockageId: Joi.string().allow(null),
Ce champ ne peut pas être présent pendant une création.

2023-10-11 11:51 UTC, tmerlier commented on backend/lib/projets-validator.js
> +      sercure: Joi.bool()
```suggestion
      secure: Joi.bool()
```

2023-10-11 11:51 UTC, tmerlier commented on backend/lib/projets-validator.js
> +      sercure: Joi.bool()
```suggestion
      secure: Joi.bool()
```

2023-10-12 13:22 UTC, jdesboeufs requested changes

2023-10-12 13:22 UTC, jdesboeufs commented on backend/lib/models/projets.js
> +  if (SCANNER_URL) {
C'est plus simple et faire ceci :
```js
if (!SCANNER_URL) {
  return [...livrables]
}

// Sinon on retourne le `Promise.all(...)`
```

2023-10-12 13:22 UTC, jdesboeufs commented on backend/lib/models/projets.js
> +      console.error(error.message)
Surtout pas car si on try/catch on perd les livrable en cas d'indispo de l'API.
De manière générale on utilise juste `console.error()` que quand on veut éventuellement avoir des billes pour débugger un truc donc on se fout qu'il réussisse ou pas.
Le try/catch devrait être à l'intérieur du Promise.all, et le catch devrait toujours renvoyer le livrable, même si on a pas réussi à trouver un stockage.

2023-10-12 13:22 UTC, jdesboeufs commented on backend/lib/models/projets.js
> +      const updatedLivrables = await Promise.all(livrables.map(async livrable => {
Un Promise.all devant des appels réseaux c'est un peu risqué.
Heureusement il n'y aura jamais des tonnes de livrables.

2023-10-12 13:22 UTC, jdesboeufs commented on backend/lib/projets-validator.js
> +  ).allow(null).messages({
Pourquoi allow null ?

2023-10-12 13:22 UTC, jdesboeufs commented on backend/lib/projets-validator.js
> +      authorization: Joi.string()
À supprimer pour le moment

2023-10-13 07:14 UTC, GllmR commented on backend/lib/models/projets.js
> +      console.error(error.message)
https://github.com/openpcrs/pcrs.beta.gouv.fr/pull/330#discussion_r1354742370

2023-10-13 07:15 UTC, GllmR commented on backend/lib/projets-validator.js
> +  ).allow(null).messages({
Parce que ce n’est pas un champ obligatoire

2023-10-13 09:15 UTC, jdesboeufs requested changes

2023-10-13 09:15 UTC, jdesboeufs commented on backend/lib/projets-validator.js
> +  ).allow(null).messages({
Pour la création tu n'as pas besoin du coup.

2023-10-13 09:15 UTC, jdesboeufs commented on backend/lib/projets-validator.js
> +    'jpeg2000_lossy',
D'où vient cette liste ? Elle n'a pas de sens.

2023-10-13 09:15 UTC, jdesboeufs commented on backend/lib/projets-validator.js
> +    'sftp'
Pas encore supporté.

2023-10-13 09:15 UTC, jdesboeufs commented on backend/lib/projets-validator.js
> +      path: Joi.string(),
`startPath`

2023-10-13 09:15 UTC, jdesboeufs commented on backend/lib/projets-validator.js
> +      port: Joi.number(),
Integer

2023-10-13 09:15 UTC, jdesboeufs commented on backend/lib/projets-validator.js
> +      host: Joi.string(),
required

2023-10-13 09:15 UTC, jdesboeufs commented on backend/lib/projets-validator.js
> +    otherwise: Joi.object({
Le otherwise ne survivra pas longtemps. Le SFTP a une différence dans les champs possibles (le secure)

2023-10-13 09:15 UTC, jdesboeufs commented on backend/lib/projets-validator.js
> +      secure: Joi.bool().default(false)
Le default ne sert à rien car tu ne retournes pas le contenu validé (c'est dommage d'ailleurs)

2023-10-13 09:15 UTC, jdesboeufs commented on scripts/migration-v04.js
> +const projets = await mongo.db.collection('projets').find({}).toArray()
Pour le futur tu pourras utiliser `for await` qui est plus pensé pour cela.

2023-10-13 09:15 UTC, jdesboeufs commented on scripts/migration-v04.js
> +        statut: 'control_en_cours'
Typo

2023-10-13 09:18 UTC, GllmR commented on backend/lib/projets-validator.js
> +    'jpeg2000_lossy',
Elle est dans le modèle de données du gitbook.

Je remets comme c’était avant.

2023-10-13 10:11 UTC, GllmR commented on backend/lib/projets-validator.js
> +  ).allow(null).messages({
Le champ n’étant pas obligatoire, si le front n’envoi pas ce champ, la validation ne passera pas. Le `allow(null)` est sur tous les champs qui ne sont pas requis.

2023-10-13 10:13 UTC, GllmR commented on backend/lib/projets-validator.js
> +      path: Joi.string(),
Tout est en snake_case, je mets `start_path` ?

2023-10-13 11:56 UTC, jdesboeufs commented on backend/lib/projets-validator.js
> +  ).allow(null).messages({
Tu confonds avec `.required()`

2023-10-13 11:57 UTC, jdesboeufs commented on backend/lib/projets-validator.js
> +      path: Joi.string(),
Non c'est les paramètres du Scan, et c'est du camelCase.

2023-10-13 13:05 UTC, jdesboeufs requested changes

2023-10-13 13:05 UTC, jdesboeufs commented on backend/lib/api-scanner.js
> +    const response = await got.post(SCANNER_URL, {
L'URL n'est pas correcte. Il manque `/storages`.
Il faut aussi définir la variables d'environnement dans le `README` et dans le `.env.sample`

2023-10-13 13:05 UTC, jdesboeufs commented on backend/lib/api-scanner.js
> +    const {_id} = response.body
Juste une remarque, il est possible d'utiliser `got` avec `.json()` ce qui simplifie légèrement la syntaxe. Mais c'est un détail.

2023-10-13 13:05 UTC, jdesboeufs commented on backend/lib/api-scanner.js
> +export async function updateLivrableStockage(livrables) {
Code à déplacer dans le modèle `projets.js` sauf l'appel à l'API.

2023-10-13 13:05 UTC, jdesboeufs commented on backend/lib/models/projets.js
> +async function addStockageId(livrables) {
Le code devrait être ici. Cette fonction ne sert à rien sinon.

2023-10-13 15:35 UTC, jdesboeufs requested changes

2023-10-13 15:35 UTC, jdesboeufs commented on backend/__tests__/projets-validator.js
> +        host: 'ftp://moi-serveur.fr'
Exemple invalide même si on ne valide pas.
On attend un nom de domaine ou une IP pas une URL

2023-10-13 15:35 UTC, jdesboeufs commented on backend/lib/models/projets.js
> +    const {_id} = await attachStorage({type, params})
Il faut quand même un try/catch ici pour gérer les rejets de l'API.

2023-10-13 17:03 UTC, jdesboeufs approved these changes

2023-10-16 08:12 UTC, merged