Ajout de la page projet
openpcrs/pcrs.beta.gouv.fr pull request #333
Opened 2023-10-11 16:54 UTC by Maxine-Le-Pennec

[Maquette FIGMA](https://www.figma.com/file/2IB2aSEpCw24oWfNrd1X4k/Visualisateur-de-fichiers?type=design&node-id=219-523&mode=design)

Todo list : 

- [ ] Affichage en lignes (partie de droite en haut)
- [ ] Afficher les informations de chaque acteurs et livrables
- [ ] Ajout d'un des actions `éditer`, `supprimer`, `gestion du lien de partage` sur la page projet
- [ ] Ajouter un point d'entrée plus visible sur la sidebar de la carte
- [ ] Ajout de la section subvention

![Capture d’écran 2023-10-11 à 18 52 09](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/71ba6597-b3cc-4903-92ec-53ccdc511850)

2023-10-13 09:08 UTC, tmerlier requested changes
Il faudrait que la page d'édition d'un projet renvoi sur la page du projet maintenant et plus sur la carte.

Et le `setTimeout` accompagné du message "Le projet a bien été modifié/créé, vous allez maintenant être redirigé vers la carte de suivi" n'est plus utile.

2023-10-13 09:59 UTC, tmerlier commented
Je me dis qu'il serait préférable de forcer l'ouverture que d'un seul wrapper à la fois sur la page projet. Car en plus d'être assez volumineux, on pourrait se retrouver avec plusieurs cartes en même temps quand on consultera les livrables. Ce qui n'est pas une super idée pour les perf.

2023-10-13 11:17 UTC, Maxine-Le-Pennec commented on pages/projet.js
> +    if (id) {
Je crois que la 404 the throw automatiquement si getProjet retourne une 404. Dans le cas contraire, il faudrait que je puisse accéder au code erreur dans l'objet error du catch.

2023-10-17 07:29 UTC, tmerlier requested changes

2023-10-17 07:29 UTC, tmerlier commented on components/list-slicer.js
> +  const [showFullList, setShowFullList] = useState(false)
Il faut choisir l'une ou l'autre, mais les deux ne sont pas utiles.

2023-10-17 07:29 UTC, tmerlier commented on components/list-slicer.js
> +        ))}
En fonction du nombre d’éléments, ça pourrait être intéressant d’utiliser un `useMemo`. Il serait aussi préférable d’éviter l'utilisation de `uniqueId` en faisant en sorte que `item` ou `renderListItem` dispose d'un `id`.

2023-10-17 07:29 UTC, tmerlier commented on components/map-sidebar/index.js
> +const SHARE_URL = process.env.NEXT_PUBLIC_PROJECT_SHARE_URL || 'https://pcrs.beta.gouv.fr'
Quelle est la particularité de cette URL ? Je suis étonné de voir que le fallback soit celle du site.

2023-10-17 07:29 UTC, tmerlier commented on components/map-sidebar/project-header.js
>        <style jsx>{`
Attention à bien supprimer le style qui pourrait ne plus être utilisé. Il n'y en a peut-être pas, mais je vois beaucoup de suppression dans le code et aucune dans le style.

2023-10-17 07:29 UTC, tmerlier commented on components/projet/index.js
> +  const {actors, subventionsNatures} = PCRS_DATA_COLORS
En dehors du composant.

2023-10-17 07:29 UTC, tmerlier commented on components/projet/index.js
> +  const {status} = PCRS_DATA_COLORS
À destructurer avec le reste.

2023-10-17 07:29 UTC, tmerlier commented on components/projet/index.js
> +const ProjetInfos = ({project}) => {
Beaucoup trop de chose dans ce composant. Chaque section devrait être un composant qui traite lui-même ces besoins.

2023-10-17 07:29 UTC, tmerlier commented on components/projet/list-render-items.js
> +    <div className='fr-mt-1w fr-grid-row'><div className='title fr-mr-1w'> Livraison :</div> <span>{livrable.date_livraison ? `le ${formatDate(livrable.date_livraison)}` : 'Non renseigné'}</span></di
```suggestion
    <div className='fr-grid-row'><div className='title fr-mr-1w'>Nature : </div> <span>{NATURES_LABELS[livrable.nature] || 'Non renseignée'}</span></div>
    <div className='fr-mt-1w fr-grid-row'><div className='title fr-mr-1w'>Licence :</div><span>{LICENCES_LABELS[livrable.licence] || 'Non renseignée'}</span></div>
    <div className='fr-mt-1w fr-grid-row'><div className='title fr-mr-1w'>Diffusion :</div> <span>{DIFFUSIONS_LABELS[livrable.diffusion] || 'Non renseignée'}</span></div>
    <div className='fr-mt-1w fr-grid-row'><div className='title fr-mr-1w'>Type de publication :</div><span>{PUBLICATIONS_LABELS[livrable.publication] || 'Non renseigné'}</span></div>
    <div className='fr-mt-1w fr-grid-row'><div className='title fr-mr-1w'> Livraison :</div> <span>{livrable.date_livraison ? `le ${formatDate(livrable.date_livraison)}` : 'Non renseignée'}</span></div>
```

2023-10-17 07:29 UTC, tmerlier commented on pages/projet/[id].js
> +}
Attention, le rendu sera donc côté serveur et il faudra charger dynamiquement le composant qui s'occupera de la carte des livrables.

2023-10-17 08:14 UTC, Maxine-Le-Pennec commented on components/map-sidebar/index.js
> +const SHARE_URL = process.env.NEXT_PUBLIC_PROJECT_SHARE_URL || 'https://pcrs.beta.gouv.fr'
`shareCodeUrl` et `editCodeUrl` sont des url destinées à être affichée à l'utilisateur.
`SHARE_URL` permet d'utiliser `http://localhost:3000` et mode dev et `https://pcrs.beta.gouv.fr` en production.
Cependant, j'ai vu que `SHARE_URL` est utilisé à pas mal d'endroit alors qu'utiliser la variable `NEXT_PUBLIC_URL `était déjà largement suffisante.


![Capture d’écran 2023-10-17 à 10 11 03](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/d3fe9034-c272-4035-a688-79548ade530e)
![Capture d’écran 2023-10-17 à 10 11 16](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/2b98e250-eb8f-4de3-8385-7f6f51db7336)

2023-10-18 14:07 UTC, tmerlier commented on components/map-sidebar/index.js
> +const SHARE_URL = process.env.NEXT_PUBLIC_PROJECT_SHARE_URL || 'https://pcrs.beta.gouv.fr'
Si `SHARE_URL` est identique à `PUBLIC_URL` alors inutile de l'utiliser.

2023-10-18 14:56 UTC, tmerlier requested changes

2023-10-18 14:56 UTC, tmerlier commented on components/projet/acteurs-section.js
> +import {ACTORS_LABELS} from '@/lib/utils/projet.js'
De la même façon que `STATUS`, les labels et couleurs des acteurs pour être rassemblé au même endroit.

2023-10-18 14:56 UTC, tmerlier commented on components/projet/index.js
> +          grid-template-columns: 7fr 3fr; /* Deux colonnes, deux occupe 70% et trois 30% */
```suggestion
          grid-template-columns: 2fr 1fr;
```

2023-10-18 14:56 UTC, tmerlier commented on components/projet/list-render-items.js
> +
L'approche n’est pas la bonne ici. On se retrouve avec des composants copiés/collés. Ça aurait valable si les listes étaient complètement différentes, mais ce n'est pas le cas.

Il nous faut simplement un composant qui affiche la liste d’item de façon neutre. Ex:
```
export const RenderItems = items => (
  <div className='content-wrapper fr-p-2w'>
    <div className='fr-grid-row'>
      {items.map(item => (
        <div key={item.id} className='fr-mt-1w fr-grid-row'>
          <div className='title fr-mr-1w'>{item.renderItem()}</div>
        </div>
      ))}
    </div>

    <style jsx>{`
        .content-wrapper {
          background: white;
          text-align: left;
          gap: 5px;
        }

        .title {
          color: ${colors.info425};
          font-weight: bold;
        }

        .content-wrapper span {
          font-weight: normal;
        }
    `}</style>
  </div>
)
```

Et ce sont les `items` qui contiennent leur propose logique d'affichage et même un id.

2023-10-18 14:56 UTC, tmerlier commented on components/projet/livrables-section.js
> +        </div>
Il faudrait au moins désactiver le champ s'il n'y a qu'un seul livrable disponible.

2023-10-18 14:56 UTC, tmerlier commented on components/projet/progression-section.js
> +      </div>
Code obsolète et en doublon avec la sidebar.

2023-10-18 14:56 UTC, tmerlier commented on components/projet/subventions-section.js
> +const {subventionsNatures} = PCRS_DATA_COLORS
De la même façon que `STATUS` et acteurs. Les labels et couleurs devraient être réunis dans une même variable dans `/lib/utils/projet.js`

2023-10-18 14:56 UTC, tmerlier commented on components/suivi-form/index.js
> +          setIsShareModalOpen(true)
Ce code est accessible sans `userRole` ou `_id` ?

2023-10-18 14:56 UTC, tmerlier commented on components/suivi-form/index.js
> +              {`Retourner à la ${_id ? 'page du projet' : 'carte de suivi'}`}
Pourquoi retourner à la carte de suivi ?

2023-10-18 14:56 UTC, tmerlier commented on components/suivi-form/index.js
> +                    {`Retourner à la ${_id ? 'page du projet' : 'carte de suivi'}`}
Idem.

2023-10-18 14:56 UTC, tmerlier commented on lib/utils/projet.js
> +export const ACTORS_LABELS = {
À compléter avec les couleurs issues de `PCRS_DATA_COLORS` de la même façon que `STATUS`.

2023-10-18 14:56 UTC, tmerlier commented on lib/utils/projet.js
> +export const NATURES_LABELS = {
À compléter avec les couleurs issues de `PCRS_DATA_COLORS` de la même façon que `STATUS`.

2023-10-18 14:56 UTC, tmerlier commented on lib/utils/projet.js
> +export const SUBVENTIONS_NATURES_LABELS = {
À compléter avec les couleurs issues de `PCRS_DATA_COLORS` de la même façon que `STATUS`.

2023-10-18 15:09 UTC, Maxine-Le-Pennec commented on components/suivi-form/index.js
> +          setIsShareModalOpen(true)
Si on est ni en édition ou pas admin, on a la modale de partage de code.
Sinon on repart sur la page du projet

2023-10-18 15:10 UTC, Maxine-Le-Pennec commented on components/suivi-form/index.js
> +              {`Retourner à la ${_id ? 'page du projet' : 'carte de suivi'}`}
On retourne à la carte de suivi et pas à la page projet parce que le projet n'existe pas encore

2023-10-18 15:11 UTC, Maxine-Le-Pennec commented on components/suivi-form/index.js
> +                    {`Retourner à la ${_id ? 'page du projet' : 'carte de suivi'}`}
On retourne à la carte de suivi et pas à la page projet parce que le projet n'existe pas encore

2023-10-18 16:07 UTC, Maxine-Le-Pennec commented on components/projet/list-render-items.js
> +
J'ai pas compris à quoi correspond `item.renderItem()`. `items` c'est quoi ? Un tableau avec le titre, le contenu et un id ?

2023-10-18 23:23 UTC, merged