Ajout du formulaire d'ajout du stockage
openpcrs/pcrs.beta.gouv.fr pull request #334
Opened 2023-10-12 18:38 UTC by Maxine-Le-Pennec

Création d'un formulaire d'ajout de stockage intégré dans le formulaire de livrable.
L'utilisateur a le choix entre un serveur HTTP et un serveur FTP

- [ ] Gestion des erreurs des inputs à la validation 
- [ ] Erreur `invalid payload` au submit (v4 en attente)
- [ ] Test

![Capture d’écran 2023-10-12 à 20 29 59](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/537c7ac4-570a-4662-ae04-837014e8bcca)
![Capture d’écran 2023-10-12 à 20 32 36](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/7fbbcf79-9fe6-451b-8702-57f99ca65cc6)

2023-10-12 20:03 UTC, jdesboeufs commented
Il manque des champs sur le FTP. Ou alors la capture n'est pas complete.

2023-10-17 13:02 UTC, Maxine-Le-Pennec reviewed
`Invalid payload `au moment du submit du formulaire si on ajouté un livrable

2023-10-18 09:51 UTC, tmerlier requested changes

2023-10-18 09:51 UTC, tmerlier commented on components/suivi-form/livrables/livrable-card.js
> +    stockage: PropTypes.string,
On peut préciser les types de stockage.
```suggestion
    stockage: PropTypes.oneOf(['http', 'ftp']),
```

Et bientôt `sftp` du coup.

2023-10-18 09:51 UTC, tmerlier commented on components/suivi-form/livrables/livrable-form.js
> +  }
Utilise plutôt une ref. 

```
const livrableFormRef = useRef()
 {...}

const handleLivrableStockage = e => {
     setLivrableStockage(e)
     livrableFormRef.current.scrollIntoView()
   }

{...}

<div ref={livrableFormRef} className='fr-mt-4w'>
```

2023-10-18 09:51 UTC, tmerlier commented on components/suivi-form/livrables/livrable-form.js
> +            </div>
Un composant dédié pourrait être une bonne chose.

2023-10-18 09:51 UTC, tmerlier commented on components/ui/timeline-step.js
> +        position={isLastStep ? 'left' : 'right'}
N’a pas grand-chose à faire dans cette PR.

2023-10-18 09:51 UTC, tmerlier commented on components/suivi-form/livrables/stockage-form/ftp-form.js
> +  const [checkedStatus, setCheckedStatus] = useState(false)
Pas besoin d'avoir une state dédier puisque la valeur est `values.secure`. On peut adapter l'initialisation pour s'assurer de lui donner une valeur.
```suggestion
  const [values, setValues] = useState({...initialValues, secure: initialValues.secure || false})
```

2023-10-18 09:51 UTC, tmerlier commented on components/suivi-form/livrables/stockage-form/ftp-form.js
> +  }
En partant du commentaire au-dessus, cette fonction ne serait plus nécessaire et tout pourrait se faire avec `handleValuesChange`.

2023-10-18 22:15 UTC, tmerlier approved these changes

2023-10-18 23:16 UTC, merged