Correction et amélioration des composants liés au stockage
openpcrs/pcrs.beta.gouv.fr pull request #347
Opened 2023-10-23 20:02 UTC by tmerlier

## Contexte
Quelques erreurs ou lourdeur dans le code se sont glissés dans les composants liés à l’affichage des stockages. Cette PR a pour objectif de les corriger et de simplifier le code.

## Évolutions
- Correction d’une coquille sur le nom du composant `<CenteredSpinner>`
- Correction de la déclaration des propTypes de `StockageData`
- Ajout d'un fichier `request.js` dans les `/utils` permettant d'uniformiser une partie des appels `fetch` de l'application
- Ajout d'un composant `<ScanResult>` dédié à l’affichage du résultat du scanner
- Utilisation de `params` issue du livrable et non de l'API Scanner qui ne le renvoi plus

2023-10-23 21:02 UTC, jdesboeufs requested changes

2023-10-23 21:02 UTC, jdesboeufs commented on lib/utils/request.js
> +    return res
Pareil. Pourquoi ?

2023-10-23 21:02 UTC, jdesboeufs commented on lib/utils/request.js
> +    return {error: content}
On throw pas d'erreur ? 😭

2023-10-23 21:02 UTC, jdesboeufs commented on lib/utils/request.js
> +  return {data: content}
⚰️

2023-10-23 21:02 UTC, jdesboeufs commented on pages/suivi-pcrs.js
> -import CenteredSpinnder from '@/components/centered-spinner.js'
🕷️

2023-10-23 21:18 UTC, tmerlier commented on lib/utils/request.js
> +    return res
J'ai gardé le code existant pour éviter de casser un comportement inatendu.

2023-10-23 21:22 UTC, tmerlier commented on lib/utils/request.js
> +    return {error: content}
On est sur le traitement spécifique des formulaires ici. Ça permet de gérer spécifiquement les erreurs de payload. 

Cela dit, on pourrait `throw` un type d'erreur spécifique pour gérer ces réponses et récupérer correctement les erreurs de payload.

2023-10-23 21:23 UTC, tmerlier commented on pages/suivi-pcrs.js
> -import CenteredSpinnder from '@/components/centered-spinner.js'
Deux fautes de typo différentes pour le même composant… 😅

2023-10-23 21:24 UTC, tmerlier commented on components/projet/stockage-preview.js
> +              {!stockage.data && ['pending', 'processing'].includes(stockage.scan) && (
Comment ça "processing aussi" ?

2023-10-24 08:39 UTC, GllmR requested changes
Quand on a pas d’id sur un stockage : 
```
Failed prop type: The prop `stockageId` is marked as required in `StockagePreview`, but its value is `null`.
```

```
`value` prop on `select` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.
```

Sur la page projet : 
```
Failed prop type: The prop `isDownloadable` is marked as required in `StockagePreview`, but its value is `undefined`.
```

2023-10-24 08:39 UTC, GllmR commented on components/projet/stockage-data.js
>       `}</style>
Problème d'indentation

2023-10-24 08:44 UTC, Maxine-Le-Pennec requested changes

2023-10-24 08:44 UTC, Maxine-Le-Pennec commented on components/projet/stockage-data.js
> +            const {label, defaultValue} = STOCKAGE_PARAMS[key]
Si le stockage est de type `http`, une erreur a lieu car `url` n'est pas géré dans `STOCKAGE_PARAMS`

```
export const STOCKAGE_PARAMS = {
  host: {label: 'Adresse du serveur', defaultValue: 'Non renseigné'},
  username: {label: 'Identifiant', defaultValue: 'Non renseigné'},
  password: {label: 'Mot de passe', defaultValue: 'Non renseigné'},
  startPath: {label: 'Chemin du répertoire', defaultValue: '/ (défaut'},
  port: {label: 'Port', defaultValue: 'Non renseigné'}
}
```

2023-10-24 08:51 UTC, tmerlier commented on components/containers/dropdown-list.js
> +const DropdownList = ({title, list, isDefaultOpen}) => {
C'est un composant d'affichage qui contient une partie de logique.

2023-10-24 08:56 UTC, Maxine-Le-Pennec reviewed
`Warning: Failed prop type: The prop `geojson` is marked as required in `ScannerMap`, but its value is `undefined`.`

2023-10-24 08:58 UTC, Maxine-Le-Pennec commented on components/containers/dropdown-list.js
> +const DropdownList = ({title, list, isDefaultOpen}) => {
Je croyais qu'on évitait d'appliquer ce système dans PCRS ?

2023-10-24 09:09 UTC, tmerlier commented on components/containers/dropdown-list.js
> +const DropdownList = ({title, list, isDefaultOpen}) => {
Ça a été commencé, mais n'a pas été suivi. Je referai une réorganisation des composants pour garder l'originale et non par type.

2023-10-24 09:12 UTC, tmerlier commented on components/projet/stockage-data.js
> +            const {label, defaultValue} = STOCKAGE_PARAMS[key]
Le filtre `['ftp', 'sftp'].includes(type))` aurait dû empêcher ça… Je regarde ce qu'il se passe.

2023-10-24 09:13 UTC, GllmR commented on components/containers/dropdown-list.js
> +const DropdownList = ({title, list, isDefaultOpen}) => {
Une partie de logique ?

En quoi ça en fait un conteneur ?

2023-10-24 09:43 UTC, tmerlier commented on lib/utils/request.js
> +    return {error: content}
@jdesboeufs je te propose de gérer ce problème dans une PR dédiée, ça te va ?

2023-10-24 09:44 UTC, tmerlier commented
> Quand on a pas d’id sur un stockage :
> 
> ```
> Failed prop type: The prop `stockageId` is marked as required in `StockagePreview`, but its value is `null`.
> ```
> 
>  ```
> `value` prop on `select` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.
> ```
> 
> Sur la page projet :
> 
> ```
> Failed prop type: The prop `isDownloadable` is marked as required in `StockagePreview`, but its value is `undefined`.
> ```

Il me semble que les deux premiers sont corrigés par cette PR https://github.com/openpcrs/pcrs.beta.gouv.fr/pull/350

2023-10-24 15:18 UTC, Maxine-Le-Pennec approved these changes

2023-10-24 16:17 UTC, merged