Ajout d’un bouton pour relancer le scan d’un stockage
openpcrs/pcrs.beta.gouv.fr pull request #364
Opened 2023-10-31 14:41 UTC by GllmR

Cette PR ajoute un bouton permettant de relancer le scan d’un stockage : 

### Backend : 
- Ajout d'une fonction qui appelle le scanner en lui fournissant le jeton d'authentification
- Ajout d'une route `/projets/:projetId/stockages/:stockageId/refresh-scan`

### Frontend : 
- Ajout d'une fonction qui appelle la route `/projets/:projetId/stockages/:stockageId/refresh-scan`
- Ajout d'un bouton dans le formulaire permettant de relancer le scan de stockage

### Captures : 

![image](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/56537238/95023884-d7d5-49ef-982f-859e432eebdf)

![image](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/56537238/696b1b24-718a-46dc-a67f-f9ab6c1f5109)

Fix #363

2023-10-31 14:45 UTC, jdesboeufs commented on lib/suivi-pcrs.js
> +  const options = buildOptions({method: 'POST', token})
C'est quoi ce token ?

2023-10-31 14:47 UTC, GllmR commented on lib/suivi-pcrs.js
> +  const options = buildOptions({method: 'POST', token})
C'est le jeton d'édition, pour pouvoir relancer le scan depuis le formulaire d'édition (rôle éditeur de projet)

2023-10-31 15:09 UTC, tmerlier requested changes
Je trouve assez étrange de mettre ce bouton dans le formulaire d'édition du projet. Ça place serait plutôt dans le panneau admin du projet lui-même. En le mettant dans le formulaire, en plus d'être peu accessible, il vient ajouter de la complexité et une logique différente d'un formulaire à un composant déjà riche.

Une fois le scan en cours, on s'attend à le voir se terminer. Faire du polling pour récupérer cette information serait une bonne chose, même si ce n'est pas non plus indispensable.

2023-10-31 15:09 UTC, tmerlier commented on components/suivi-form/livrables/livrable-card.js
> +  }
Il serait préférable de définir cette méthode au niveau du formulaire et de la passer en `props` à la place de la paire `projectId` et `editCode`.

Ensuite, l'erreur pourra être gérée avec les erreurs dédiées à ce formulaire.

2023-10-31 15:09 UTC, tmerlier commented on components/suivi-form/livrables/livrable-card.js
> +                {refreshedScan ? 'Scan relancé' : 'Relancer le scan'}
```suggestion
                {refreshedScan ? 'Scan en cours…' : 'Relancer le scan'}
```

2023-10-31 15:14 UTC, GllmR commented
> Je trouve assez étrange de mettre ce bouton dans le formulaire d'édition du projet. Ça place serait plutôt dans le panneau admin du projet lui-même. En le mettant dans le formulaire, en plus d'être peu accessible, il vient ajouter de la complexité et une logique différente d'un formulaire à un composant déjà riche.
> 
> Une fois le scan en cours, on s'attend à le voir se terminer. Faire du polling pour récupérer cette information serait une bonne chose, même si ce n'est pas non plus indispensable.

Effectivement, il serait mieux dans la page projet, malheureusement, il faut qu'une personne disposant du lien d'édition puisse relancer un scan et actuellement, c'est le seul endroit accessible avec le lien d'édition de projet.

2023-10-31 16:09 UTC, tmerlier approved these changes

2023-11-02 13:44 UTC, tmerlier approved these changes

2023-11-02 13:44 UTC, tmerlier commented on components/suivi-form/livrables/stockage-refresh.js
> +        onClick={() => handleClick()}
La arrow fonction n'est pas utile ici.
```suggestion
        onClick={handleClick}
```

2023-11-02 13:44 UTC, tmerlier commented on components/suivi-form/livrables/stockage-refresh.js
> +        {isScanRefreshing ? 'Scan en cours…' : 'Relancer le scan'}
Comme il n'y a pas de système de mise à jour de l'état de scan, il serait peut-être préférable de simplement indiquer quelque chose comme "Le scan va être lancé prochainement" en plus concis.

2023-11-02 13:58 UTC, merged