Ajout du formulaire de suivi [WIP]
openpcrs/pcrs.beta.gouv.fr pull request #86
Opened 2023-02-22 15:34 UTC by Maxine-Le-Pennec

Cette PR ajoute le formulaire du suivi PCRS comprenant différentes sections 

1. Informations générales sur le pcrs : 
- Nom
- Régime
- Nature

<img width="1439" alt="Capture d’écran 2023-02-22 à 16 18 44" src="https://user-images.githubusercontent.com/66621960/220668638-c5bbf280-7671-4f9f-a193-733720652412.png">

2. Livrables : un livrable doit au moins avoir été ajouté avant l'envoi du formulaire.
<img width="1425" alt="Capture d’écran 2023-02-22 à 16 19 15" src="https://user-images.githubusercontent.com/66621960/220668716-4103ffc6-b3fd-4250-84d0-7c549a16c2ca.png">

3. Acteurs : un acteur doit au moins avoir été ajouté avant l'envoi du formulaire.
L'acteur peut être recherché à l'aide de champs de suggestions. Lorsque l'acteur est sélectionné, le champ SIREN se rempli automatiquement
<img width="1425" alt="Capture d’écran 2023-02-22 à 16 20 13" src="https://user-images.githubusercontent.com/66621960/220669003-4ec59520-c5f4-4350-8fc4-ed63d226fc48.png">

4. Périmètres : un périmètre doit au moins avoir été ajouté à l'envoi du formulaire
<img width="1434" alt="Capture d’écran 2023-02-22 à 16 20 44" src="https://user-images.githubusercontent.com/66621960/220669900-fe8d2d2e-9d51-4091-a798-9e1cd9e37f9f.png">

6. Étapes : la date de l'étape initiale doit au moins être renseigné.
L'ajout d'une étape est balisé et suit l'ordre suivant : `investigation` => `production` => `produit` => `livré` => `obsolète`

<img width="1359" alt="Capture d’écran 2023-02-22 à 16 21 02" src="https://user-images.githubusercontent.com/66621960/220669704-ea7e2ac2-bad1-44d4-8b91-f0981aedef65.png">

7. Subventions : non-obligatoire 
<img width="1422" alt="Capture d’écran 2023-02-22 à 16 21 31" src="https://user-images.githubusercontent.com/66621960/220671495-ef374040-8840-4f2b-a7b3-0c7d68a42774.png">

### **Formulaire valide**
![Movavi ScreenShot 067 - Accompagnement national du PCRS - pcrs beta gouv fr - localhost](https://user-images.githubusercontent.com/66621960/220671710-8fa87b5b-f6a5-41ae-a4ad-aa9d66e1cc63.jpg)

**Cette page pourra être mergée lorsque :** 
- [ ] L'API sera mise en place
- [ ] L'accès au formulaire disposera d'un point d'entrée

2023-02-23 10:05 UTC, GllmR requested changes
- Le composant autocomplete renvoie une erreur
- L'autocompletion déplace / agrandi son conteneur (position absolute)
- En version mobile, les champs "nom" ne prennent pas toute la largeur

2023-03-21 20:16 UTC, jdesboeufs requested changes

2023-03-21 20:16 UTC, jdesboeufs commented on lib/suivi-pcrs.js
> +const ADMIN_TOKEN = process.env.NEXT_PUBLIC_ADMIN_TOKEN
C'est un jeton privé. Il n'a pas à être accessible via les variables d'environnements.
C'est à l'utilisateur de le saisir via un écran ou une URL.

2023-03-21 20:16 UTC, jdesboeufs commented on lib/suivi-pcrs.js
> +    const response = await fetch('http://localhost:3000/projets', {
localhost ?
Juste `/projets`

2023-03-23 10:33 UTC, closed without merging