Export & Mise à jour de la validation des projets de suivi
openpcrs/pcrs.beta.gouv.fr pull request #93
Opened 2023-02-27 10:07 UTC by GllmR

Cette PR exporte et mets à jour la validation des projets : 
- Installation de `https-errors`
- Exportation et mises à jour des règles de validation des projets
- Mise à jour de la fonction `getTerritoriesName` vers `getTerritoryInfos` (Renvoi maintenant la chaine originale et les infos disponibles)
- Mise à jour de l’affichage des territoires suite à la modification précédente

2023-02-28 10:29 UTC, jdesboeufs requested changes

2023-02-28 10:29 UTC, jdesboeufs commented on lib/build-geometry.js
> +    getTerritoryInfos(territory) {
`codeTerritoire`
`getTerritoire`

Renvoie le contenu de `properties` et c'est tout.

Sinon je trouve ça trop complexe.

2023-02-28 10:29 UTC, jdesboeufs commented on lib/projets-validator.js
> +  return update
Pourquoi retourner `update` ?

Par ailleurs `update` est plutôt un verbe. On utilise davantage `changes`.

2023-02-28 11:03 UTC, GllmR commented on lib/projets-validator.js
> +  return update
Je pensais que ce serait une bonne idée de renvoyer le projet mis à jour 🤷
Je devrais retourner quoi ? Juste un code ?

Effectivement, le nom serait plutôt `updatedProjet` (si je dois le laisser)

2023-03-03 10:29 UTC, jdesboeufs requested changes

2023-03-03 10:29 UTC, jdesboeufs commented on lib/__tests__/projets-validator.js
> +const unvalidProjet = {
invalidProjet

2023-03-03 10:29 UTC, jdesboeufs commented on lib/__tests__/projets-validator.js
> +test('Create unvalid projet', t => {
Tu ne testes pas les erreurs rencontrées ?

2023-03-03 10:29 UTC, jdesboeufs commented on package.json
> +    "timeout": "1m"
Anormal.
Quel traitement prend 1 minutes ici ?

2023-03-03 10:29 UTC, jdesboeufs commented on lib/projets-validator.js
> +  return true
Pourquoi `true` ?

2023-03-03 10:29 UTC, jdesboeufs commented on lib/projets-validator.js
> +const schemaUpdate = Joi.object({
Idéalement chaque règle peut être recyclé plutôt que dupliquée. Sinon risque d'oubli lors d'une MAJ.

Pas critique.

2023-03-03 10:29 UTC, jdesboeufs commented on lib/build-geometry.js
> +      if (!territoireProperties) {
C'est un peu à l'envers.

```js
const territoire = featuresIndex.get(codeTerritoire)

if (!territoire) {
  throw new Error('Territoire not found: ' + codeTerritoire)
}

return territoire.properties
```

2023-03-07 12:44 UTC, jdesboeufs requested changes

2023-03-07 12:44 UTC, jdesboeufs commented on lib/projets-validator.js
> +  }
La fonction doit retourner la valeur sinon la validation est rejetée.

2023-03-07 13:06 UTC, merged